#!/bin/bash

chown="/usr/sbin/chown"
chmod="/bin/chmod"

${chown} -R root:gaussian /Applications/g09/
${chown} -R root:gaussian /Applications/gv/
${chmod} -R 770 /Applications/g09/
${chmod} -R 770 /Applications/gv/

exit
